import asyncio
import json
from pathlib import Path

from textual.widgets import Input, OptionList, Static

import lychee_alphadesk.tui.app as tui_app
from lychee_alphadesk.core.config import set_openai_compatible_llm
from lychee_alphadesk.core.live_data import PullResult
from lychee_alphadesk.tui.app import AlphaDeskApp


def test_dashboard_shows_cached_live_data_summary(tmp_path: Path) -> None:
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    (data_dir / "market-prices.json").write_text(
        json.dumps(
            {
                "provider": "alpha_vantage",
                "rows": [
                    {
                        "symbol": "AAPL",
                        "date": "2026-07-02",
                        "close": 214.33,
                        "volume": 51230000,
                        "currency": "USD",
                    }
                ],
            }
        ),
        encoding="utf-8",
    )

    async def run_case() -> None:
        app = AlphaDeskApp(output_dir=tmp_path)
        async with app.run_test() as pilot:
            await pilot.pause()
            dashboard = app.query_one("#dashboard-summary", Static)
            text = str(dashboard.content)
            assert "Live cache" in text
            assert "AAPL" in text
            assert "214.33" in text

    asyncio.run(run_case())


def test_dashboard_has_keyboard_action_menu(tmp_path: Path) -> None:
    async def run_case() -> None:
        app = AlphaDeskApp(output_dir=tmp_path)
        async with app.run_test() as pilot:
            await pilot.pause()
            menu = app.query_one("#action-menu", OptionList)
            assert menu.highlighted == 0
            assert "Today Discovery" in str(menu.get_option_at_index(0).prompt)

            await pilot.press("down")
            await pilot.pause()

            assert menu.highlighted == 1

    asyncio.run(run_case())


def test_dashboard_today_discovery_requires_llm_configuration(
    monkeypatch, tmp_path: Path
) -> None:
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path / "config-home"))

    async def run_case() -> None:
        app = AlphaDeskApp(output_dir=tmp_path)
        async with app.run_test() as pilot:
            await pilot.press("enter")
            await pilot.pause()

            status = app.query_one("#action-status", Static)
            text = str(status.content)
            assert "LLM provider is not configured" in text
            assert "lychee setup llm set" in text
            assert not (tmp_path / "data" / "discovery-today.json").exists()
            assert not app.query(Input)

    asyncio.run(run_case())


def test_dashboard_today_discovery_action_writes_report_when_llm_configured(
    monkeypatch, tmp_path: Path
) -> None:
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path / "config-home"))
    set_openai_compatible_llm(
        "https://llm.example.com/v1",
        "sk-demo-secret",
        "demo-model",
    )

    def fake_post(
        url: str,
        headers: dict[str, str],
        body: dict[str, object],
    ) -> object:
        return {
            "choices": [
                {
                    "message": {
                        "content": """
                        {
                          "themes": [
                            {
                              "name": "TUI model theme",
                              "markets": ["US", "HK", "CN"],
                              "summary": "Model generated this TUI theme.",
                              "evidence": ["LLM response"],
                              "sectors": ["Technology"],
                              "risk_flags": ["Model uncertainty"],
                              "confidence": "medium"
                            }
                          ],
                          "candidates": [
                            {
                              "display_name": "TUI model candidate",
                              "symbol": "NVDA",
                              "market": "US",
                              "asset_type": "stock",
                              "related_theme": "TUI model theme",
                              "why_watch": "Generated by the model.",
                              "evidence": ["LLM response"],
                              "risk_flags": ["Model uncertainty"],
                              "next_actions": ["Pull filings"],
                              "confidence": "medium",
                              "recommendation": "research"
                            }
                          ],
                          "warnings": [],
                          "next_actions": ["Review model evidence"]
                        }
                        """
                    }
                }
            ]
        }

    monkeypatch.setattr("lychee_alphadesk.core.llm._post_json", fake_post)

    async def run_case() -> None:
        app = AlphaDeskApp(output_dir=tmp_path)
        async with app.run_test() as pilot:
            await pilot.press("enter")
            await pilot.pause()

            status = app.query_one("#action-status", Static)
            text = str(status.content)
            assert "Today Discovery" in text
            assert "Mode: llm-synthesized" in text
            assert "TUI model theme" in text
            assert "Not investment advice" in text
            assert (tmp_path / "data" / "discovery-today.json").exists()
            assert not app.query(Input)

    asyncio.run(run_case())


def test_dashboard_market_menu_action_pulls_prices(
    monkeypatch, tmp_path: Path
) -> None:
    calls: list[list[str]] = []

    def fake_pull_market_prices(**kwargs: object) -> PullResult:
        calls.append(kwargs["symbols"])  # type: ignore[arg-type]
        return PullResult(
            domain="market",
            provider="alpha_vantage",
            count=2,
            output_path=tmp_path / "data" / "market-prices.json",
            warnings=[],
        )

    monkeypatch.setattr(tui_app, "pull_market_prices", fake_pull_market_prices)

    async def run_case() -> None:
        app = AlphaDeskApp(output_dir=tmp_path)
        async with app.run_test() as pilot:
            await pilot.press("down")
            await pilot.pause()
            await pilot.press("enter")
            await pilot.pause()
            app.query_one("#symbols-input", Input)

            await pilot.press(*"AAPL,TSLA")
            await pilot.press("enter")
            await pilot.pause()

            assert calls == [["AAPL", "TSLA"]]
            status = app.query_one("#action-status", Static)
            assert "Pulled market prices: 2" in str(status.content)

    asyncio.run(run_case())


def test_dashboard_symbol_prompt_handles_empty_submit(tmp_path: Path) -> None:
    async def run_case() -> None:
        app = AlphaDeskApp(output_dir=tmp_path)
        async with app.run_test() as pilot:
            await pilot.press("down")
            await pilot.pause()
            await pilot.press("enter")
            await pilot.pause()
            app.query_one("#symbols-input", Input)

            await pilot.press("enter")
            await pilot.pause()

            status = app.query_one("#action-status", Static)
            assert "No symbols entered." in str(status.content)
            app.query_one("#symbols-input", Input)

    asyncio.run(run_case())


def test_dashboard_disables_textual_command_palette(tmp_path: Path) -> None:
    async def run_case() -> None:
        app = AlphaDeskApp(output_dir=tmp_path)
        async with app.run_test() as pilot:
            await pilot.press("ctrl+p")
            await pilot.pause()

            assert app.screen.id != "--command-palette"

    asyncio.run(run_case())
